### ISSUE TITLE
ReferenceError: setTimeout is not defined

### ISSUE THREAD

**Issue by chrisdobler** [gilbox/react-spark-scroll#18]
I keep getting this issue.

I'm including the library like this:

```
var {SparkScroll, SparkProxy, sparkScrollFactory} =
  require('react-spark-scroll-gsap')({
    invalidateAutomatically: true
  });
```

```
            <SparkProxy.div proxyId="parallax" className="parallax-cont">
              <SparkScroll.div
              className="parallax-img"
              proxy="parallax"
              timeline={{
                topBottom: {transform: 'translate3d(0px,000px,0px)'},
                bottomTop: {transform: 'translate3d(0px,600px,0px)'}
              }}>
...
              </SparkScroll.div>
            </SparkProxy.div>
```

**Comment by gilbox** [comment]
are you rendering on the server? provide more info about the error

**Comment by chrisdobler** [comment]
I'm new to react, so let me try to explain the best I can. I have server rendering set up, but I'm not using it at the moment. I'm using webpack to build up the js which I'm running on a rails app. I'm not sure what other relevant information I can provide. Thanks!

**Comment by gilbox** [comment]
start w/a stack trace.

**Comment by chrisdobler** [comment]
On a related note, do you have any suggestions to get a more useful stack trace?

```
ExecJS::ProgramError - ReferenceError: setTimeout is not defined:
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:98:in `wrap_error'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:73:in `lock'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/runtime.rb:57:in `compile'
23:42:10 rails.1               |   execjs (2.7.0) lib/execjs/module.rb:27:in `compile'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/server_rendering/exec_js_renderer.rb:10:in `initialize'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/server_rendering/sprockets_renderer.rb:25:in `initialize'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/server_rendering.rb:22:in `create_renderer'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/server_rendering.rb:12:in `block in reset_pool'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:169:in `try_create'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:77:in `block in pop'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool/timed_stack.rb:76:in `pop'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool.rb:89:in `checkout'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool.rb:61:in `block in with'
23:42:10 rails.1               |   connection_pool (2.2.0) lib/connection_pool.rb:60:in `with'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/server_rendering.rb:16:in `render'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/rails/component_mount.rb:33:in `block in react_component'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:202:in `with_output_buffer'
23:42:10 rails.1               |   haml (4.0.7) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/helpers/capture_helper.rb:38:in `capture'
23:42:10 rails.1               |   haml (4.0.7) lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/helpers/tag_helper.rb:106:in `content_tag'
23:42:10 rails.1               |   haml (4.0.7) lib/haml/helpers/action_view_mods.rb:61:in `content_tag_with_haml'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/rails/component_mount.rb:48:in `react_component'
23:42:10 rails.1               |   react-rails (1.8.0) lib/react/rails/view_helper.rb:21:in `react_component'
23:42:10 rails.1               |   app/views/spree/home/index.haml:1:in `_d20f974b7641fd461258253e23883000'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/template.rb:145:in `block in render'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/template.rb:333:in `instrument'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/template.rb:143:in `render'
23:42:10 rails.1               |   deface (1.0.2) lib/deface/action_view_extensions.rb:41:in `render'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/template_renderer.rb:14:in `render'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:46:in `render_template'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/renderer/renderer.rb:27:in `render'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/rendering.rb:100:in `_render_template'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/streaming.rb:217:in `_render_template'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/rendering.rb:83:in `render_to_body'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/abstract_controller/rendering.rb:25:in `render'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:16:in `render'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
23:42:10 rails.1               |   /Users/chris/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/core_ext/benchmark.rb:12:in `ms'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:44:in `block in render'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
23:42:10 rails.1               |   activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:43:in `render'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/implicit_render.rb:5:in `send_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:198:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/rendering.rb:10:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:117:in `call'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:505:in `call'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/rescue.rb:29:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/notifications.rb:164:in `instrument'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
23:42:10 rails.1               |   activerecord (4.2.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/abstract_controller/base.rb:137:in `process'
23:42:10 rails.1               |   actionview (4.2.7.1) lib/action_view/rendering.rb:30:in `process'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal.rb:196:in `dispatch'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_controller/metal.rb:237:in `block in action'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:43:in `serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/railtie.rb:194:in `method_missing'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/routing/mapper.rb:51:in `serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:43:in `block in serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/journey/router.rb:30:in `serve'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/routing/route_set.rb:817:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/rack/developer_mode.rb:48:in `traced_call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   bullet (5.1.1) lib/bullet/rack.rb:10:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
23:42:10 rails.1               |   warden (1.2.6) lib/warden/manager.rb:34:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/etag.rb:24:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/head.rb:13:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/flash.rb:260:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/cookies.rb:560:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   activerecord (4.2.7.1) lib/active_record/query_cache.rb:36:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   activerecord (4.2.7.1) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   activerecord (4.2.7.1) lib/active_record/migration.rb:377:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/callbacks.rb:81:in `run_callbacks'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/reloader.rb:73:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
23:42:10 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
23:42:10 rails.1               |   better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rollbar (2.12.0) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
23:42:10 rails.1               |   rollbar (2.12.0) lib/rollbar.rb:735:in `scoped'
23:42:10 rails.1               |   rollbar (2.12.0) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
23:42:10 rails.1               |   rollbar (2.12.0) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   web-console (3.3.0) lib/web_console/middleware.rb:131:in `call_app'
23:42:10 rails.1               |   web-console (3.3.0) lib/web_console/middleware.rb:28:in `block in call'
23:42:10 rails.1               |   web-console (3.3.0) lib/web_console/middleware.rb:18:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/rack/logger.rb:38:in `call_app'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `block in call'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `block in tagged'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/tagged_logging.rb:68:in `tagged'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/rack/logger.rb:20:in `call'
23:42:10 rails.1               |   quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/request_id.rb:21:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/runtime.rb:18:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   activesupport (4.2.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/lock.rb:17:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   actionpack (4.2.7.1) lib/action_dispatch/middleware/static.rb:120:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/engine.rb:518:in `call'
23:42:10 rails.1               |   railties (4.2.7.1) lib/rails/application.rb:165:in `call'
23:42:10 rails.1               |   newrelic_rpm (3.16.0.318) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
23:42:10 rails.1               |   rack (1.6.4) lib/rack/content_length.rb:15:in `call'
23:42:10 rails.1               |   puma (3.6.0) lib/puma/configuration.rb:225:in `call'
23:42:10 rails.1               |   puma (3.6.0) lib/puma/server.rb:578:in `handle_request'
23:42:10 rails.1               |   puma (3.6.0) lib/puma/server.rb:415:in `process_client'
23:42:10 rails.1               |   puma (3.6.0) lib/puma/server.rb:275:in `block in run'
23:42:10 rails.1               |   puma (3.6.0) lib/puma/thread_pool.rb:116:in `block in spawn_thread'
```

**Comment by gilbox** [comment]
your code is not running in a browser, it is using ruby_racer and that is not supported by this project.

**Comment by chrisdobler** [comment]
thanks gilbox, so disappointing :( I love your project. Guess I'll have to stop treating React as a second class citizen.
